/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2018-02-11 14:09:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import feedreader.TweetVO;
import java.text.SimpleDateFormat;;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"slds/assets/styles/salesforce-lightning-design-system.css\">\r\n");
      out.write("<title>Salesforce Tweets</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class='slds-page-header' role=\"banner\">\r\n");
      out.write("\t\t<div class=\"slds-media slds-media--center\">\r\n");
      out.write("\t\t\t<div class=\"slds-media__body\">\r\n");
      out.write("\t\t\t\t<p class=\"slds-pageheader__title slds-align-middle\">\r\n");
      out.write("\t\t\t\t\t<img src=\"slds/assets/Twitter_Circle.png\" alt=\"Twitter logo\" height=\"52\" width=\"52\"/>\r\n");
      out.write("\t\t\t\t\t&nbsp;Welcome to the Salesforce Twitter Feed Reader App! \r\n");
      out.write("\t\t\t\t\t<img src=\"slds/assets/salesforce-logo.png\" alt=\"Salesforce logo\" height=\"80\" width=90\" />\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");

	boolean emptyString = request.getAttribute("noSearchString")!= null && request.getAttribute("noSearchString").equals("true");
	boolean emptyResultSet =  request.getAttribute("noResults") != null && request.getAttribute("noResults").equals("true");
	
      out.write("\r\n");
      out.write("\t<div class=\"slds-grid\">\r\n");
      out.write("\t\t<div class=\"slds-col\">\r\n");
      out.write("\t\t<div style= \"padding-left: 20px\">\r\n");
      out.write("\t\t<br/><br/><br/>\r\n");
      out.write("\t\tThis application is built as part of the Twitter Challenge Coding assessment.\r\n");
      out.write("\t\t<br/><br/><br/>\r\n");
      out.write("\t\tObjective : <br/>\r\n");
      out.write("\t\t&nbsp;&nbsp;1. Display the 10 latest tweets by user @salesforce <br/>\r\n");
      out.write("\t\t&nbsp;&nbsp;2. User should also be able to search the tweets for a word of their choice<br/>\r\n");
      out.write("\t\t&nbsp;&nbsp;3. Each minute the tweets will automatically update to show the most recent 10 tweets</pre>\r\n");
      out.write("\t\t<br/><br/>\r\n");
      out.write("\t\tThe source code is available on Github.\r\n");
      out.write("\t\t<br/><br/>\r\n");
      out.write("\t\t<form action=\"TweetReaderServlet\" method=\"post\">\r\n");
      out.write("\t\t\t<div class=\"slds-button\" >\r\n");
      out.write("\t\t\t\t<button class=\"slds-button_brand\" type=\"submit\"\tname=\"action\" value=\"fetch\">Fetch latest tweets</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br/><br/>\r\n");
      out.write("\t\t\t");
 if(emptyResultSet && !emptyString) { 
      out.write("\r\n");
      out.write("\t\t\t<div class=\"slds-notify slds-notify_alert slds-theme_alert-texture slds-theme_warning\" role=\"alert\">\r\n");
      out.write("\t\t\t  <span class=\"slds-assistive-text\">warning</span>\r\n");
      out.write("\t\t\t   <h2>Your search filtered no specific tweets</h2>\r\n");
      out.write("\t\t\t  <button class=\"slds-button slds-notify__close slds-button_icon-inverse\" title=\"Close\">\r\n");
      out.write("\t\t\t    <svg class=\"slds-button__icon\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t      <use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"/assets/icons/utility-sprite/svg/symbols.svg#close\" />\r\n");
      out.write("\t\t\t    </svg>\r\n");
      out.write("\t\t\t    <span class=\"slds-assistive-text\">Close</span>\r\n");
      out.write("\t\t\t  </button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
} if(emptyResultSet && emptyString) { 
      out.write("\r\n");
      out.write("\t\t\t<div class=\"slds-notify slds-notify_alert slds-theme_alert-texture slds-theme_error\" role=\"alert\">\r\n");
      out.write("\t\t\t  <h2>Please enter in the text box the word you wish to search for</h2>\r\n");
      out.write("\t\t\t  <button class=\"slds-button slds-notify__close slds-button_icon-inverse\" title=\"Close\">\r\n");
      out.write("\t\t\t    <svg class=\"slds-button__icon\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t      <use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"/assets/icons/utility-sprite/svg/symbols.svg#close\" />\r\n");
      out.write("\t\t\t    </svg>\r\n");
      out.write("\t\t\t    <span class=\"slds-assistive-text\">Close</span>\r\n");
      out.write("\t\t\t  </button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t<div class=\"slds-form-element \">\r\n");
      out.write("\t\t    \t<div class=\"slds-form-element__control\">\r\n");
      out.write("\t\t   \t\t\t<textarea name =\"input\" id=\"textarea-id-01\" class=\"slds-textarea\" placeholder=\"Enter search string to filter latest tweets here\"></textarea>\r\n");
      out.write("\t\t \t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<div class=\"slds-button\" >\r\n");
      out.write("\t\t\t\t<button class=\"slds-button_brand\" type=\"submit\"\tname=\"action\" value=\"search\">Search tweets</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<div class=\"slds-col slds-size_2-of-3\">\r\n");
      out.write("\t\t<div style= \"padding-left: 100px\">\r\n");
      out.write("\t\t");

		response.setIntHeader("Refresh", 60);
		List<TweetVO> tweetList = (List<TweetVO>) request.getAttribute("tweetlist");
		if(tweetList != null) {
		 for(TweetVO tweet : tweetList) {  
		
      out.write("\t\r\n");
      out.write("\t\t<div class=\"slds-medium-size_1-of-2\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<article class=\"slds-card\">\r\n");
      out.write("\t  \t<div class=\"slds-card__header slds-grid\">\r\n");
      out.write("\t    <header class=\"slds-media slds-media_center slds-has-flexi-truncate\">\r\n");
      out.write("\t      <div class=\"slds-media__figure\">\r\n");
      out.write("\t         <span class=\"slds-avatar_medium\">\r\n");
      out.write("\t  \t\t\t<img alt=\"Person name\" src=\"");
      out.print(tweet.getProfilePic() );
      out.write("\" title=\"User profile image\" />\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      <div class=\"slds-media__body\">\r\n");
      out.write("\t        <h2>\r\n");
      out.write("\t          <a href=\"javascript:void(0);\" class=\"slds-card__header-link slds-truncate\" title=\"[object Object]\">\r\n");
      out.write("\t            <span class=\"slds-text-heading_small\">&nbsp;");
      out.print( tweet.getUserName() );
      out.write(" <br/> @ ");
      out.print( tweet.getScreenName());
      out.write("</span>\r\n");
      out.write("\t          </a>\r\n");
      out.write("\t        </h2>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </header>\r\n");
      out.write("\t    <div class=\"slds-no-flex\">\r\n");
      out.write("\t     ");

	     	SimpleDateFormat formatter = new SimpleDateFormat("hh:mm a - dd MMM yyyy");
	     	String formattedDate = formatter.format(tweet.getTweetDate());
	     
      out.write("\r\n");
      out.write("\t     <span class=\"slds-badge\"> ");
      out.print(formattedDate );
      out.write(" </span>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"slds-card__body slds-card__body_inner\"> ");
      out.print(tweet.getTweetContent() );
      out.write("\r\n");
      out.write("\t  ");

	   if(tweet.getTweetImages() != null && tweet.getTweetImages().length > 0) {
	  	for(int j=0, count=0;j<tweet.getTweetImages().length && count <= 5;j++) {
	  		String temp[] = tweet.getTweetImages();
	  
      out.write("\r\n");
      out.write("\t  \t <img src=\"");
      out.print(temp[j]);
      out.write("\" alt=\"Tweet img\" height=\"500\" width=\"500\"/><br/>\r\n");
      out.write("\t  ");
}} 
      out.write("\r\n");
      out.write("\t  \r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <img src=\"slds/assets/retweet.png\" alt=\"Twitter logo\" height=\"52\" width=\"52\"/>\r\n");
      out.write("\t   ");
      out.print(tweet.getTimesRetweeted() );
      out.write("\r\n");
      out.write("\t   </article>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t");
}} 
      out.write("\r\n");
      out.write("\t\t<br/><br/><br/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
